"use client";

import { createClient, RealtimeChannel } from "@supabase/supabase-js";
import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { ChatProductCard } from "@/components/support/chat-product-card";
import type { Product } from "@/types/catalog";

type Message = { id: string; sender_type: "CUSTOMER" | "AI" | "ADMIN" | "SYSTEM"; content_type?: "TEXT" | "PRODUCT_CARD" | "PRODUCT_CAROUSEL" | "ACTION_RESULT"; payload?: { products?: Array<{ product_id: string; variant_id?: string }> }; content: string; created_at: string; delivery_status?: string };
type Conversation = { id: string; mode: "AI_ACTIVE" | "HUMAN_ACTIVE" | "AI_PAUSED" | "RESOLVED"; status: string; ai_pending?: boolean; ai_status?: "DEBOUNCING" | "QUEUED" | "PROCESSING" | "TYPING_DELAY" | null; messages?: Message[] };

function chronological(messages: Message[] = []) {
  // Laravel's ordered UUIDs preserve creation order even for legacy replies
  // written by queue workers that used a different timezone.
  return [...messages].sort((left, right) => left.id.localeCompare(right.id));
}

export function ChatWidget() {
  const pathname = usePathname(); const router = useRouter(); const dedicated = pathname === "/support";
  const [open, setOpen] = useState(false); const [conversation, setConversation] = useState<Conversation | null>(null); const [messages, setMessages] = useState<Message[]>([]);
  const [text, setText] = useState(""); const [busy, setBusy] = useState(false); const [connection, setConnection] = useState<"connecting" | "connected" | "reconnecting" | "error">("connecting");
  const [aiPending, setAiPending] = useState(false); const [aiStatus, setAiStatus] = useState<Conversation["ai_status"]>(null);
  const [cardProducts, setCardProducts] = useState<Record<string, Product>>({});
  const bottom = useRef<HTMLDivElement>(null);
  const load = useCallback(async () => {
    try { const response = await fetch("/api/support/conversation", { cache: "no-store" }); if (!response.ok) throw new Error(); const body = await response.json(); setConversation(body.data); setMessages(chronological(body.data?.messages)); setAiPending(Boolean(body.data?.ai_pending)); setAiStatus(body.data?.ai_status ?? null); setConnection("connected"); }
    catch { setConnection((value) => value === "connected" ? "reconnecting" : "error"); }
  }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  useEffect(() => { if (pathname !== "/support") sessionStorage.setItem("alas_support_origin", pathname); }, [pathname]);
  useEffect(() => { if ((!open && !dedicated) || !conversation) return; const timer = window.setInterval(load, aiPending ? 1500 : 4000); return () => window.clearInterval(timer); }, [open, dedicated, conversation, aiPending, load]);
  useEffect(() => {
    if (!open && !dedicated) return;
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    return () => { document.body.style.overflow = previousOverflow; };
  }, [open, dedicated]);
  useEffect(() => {
    const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const key = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY; const conversationId = conversation?.id; if (!conversationId || !url || !key) return;
    const client = createClient(url, key); const channel: RealtimeChannel = client.channel(`support:${conversationId}`).on("broadcast", { event: "*" }, () => void load()).subscribe((status) => setConnection(status === "SUBSCRIBED" ? "connected" : "reconnecting"));
    return () => { void client.removeChannel(channel); };
  }, [conversation?.id, load]);
  useEffect(() => { bottom.current?.scrollIntoView({ behavior: "smooth" }); }, [messages, open, dedicated]);
  const cardIds = useMemo(() => [...new Set(messages.flatMap((message) => message.payload?.products?.map((product) => product.product_id) ?? []))], [messages]);
  useEffect(() => { if (!cardIds.length) return; void fetch(`/api/support/products?ids=${encodeURIComponent(cardIds.join(","))}`, { cache: "no-store" }).then(async (response) => response.ok ? response.json() : null).then((body) => { if (body?.data) setCardProducts(Object.fromEntries((body.data as Product[]).map((product) => [product.id, product]))); }).catch(() => undefined); }, [cardIds]);

  async function start() {
    const path = window.location.pathname === "/support" ? sessionStorage.getItem("alas_support_origin") ?? "/support" : window.location.pathname; const match = path.match(/^\/products\/([^/]+)/);
    setBusy(true); try { const response = await fetch("/api/support/conversation", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ context: { page_path: path, product_slug: match ? decodeURIComponent(match[1]) : undefined } }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message); setConversation(body.data); setMessages(chronological(body.data.messages)); setAiPending(Boolean(body.data.ai_pending)); setAiStatus(body.data.ai_status ?? null); setConnection("connected"); } catch { setConnection("error"); } finally { setBusy(false); }
  }
  async function send(event: FormEvent) {
    event.preventDefault(); const content = text.trim(); if (!content || busy || !conversation) return; const clientMessageId = crypto.randomUUID();
    const optimistic: Message = { id: clientMessageId, sender_type: "CUSTOMER", content, created_at: new Date().toISOString(), delivery_status: "PENDING" }; setMessages((items) => [...items, optimistic]); setText(""); setBusy(true); if (conversation.mode === "AI_ACTIVE") { setAiPending(true); setAiStatus("DEBOUNCING"); }
    try { const response = await fetch("/api/support/conversation", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ content, clientMessageId }) }); const body = await response.json(); if (!response.ok) throw new Error(); setMessages((items) => items.map((item) => item.id === clientMessageId ? body.data : item)); window.setTimeout(() => void load(), 350); }
    catch { setMessages((items) => items.map((item) => item.id === clientMessageId ? { ...item, delivery_status: "FAILED" } : item)); setAiPending(false); setAiStatus(null); }
    finally { setBusy(false); }
  }
  const human = conversation?.mode === "HUMAN_ACTIVE" || conversation?.mode === "AI_PAUSED";
  const aiTyping = aiPending && aiStatus !== "DEBOUNCING";
  return <>
    {!dedicated && <><Link href="/support" className="fixed bottom-5 right-5 z-50 flex min-h-12 items-center gap-2 rounded-full border border-white/15 bg-gradient-to-r from-black via-[#1b1b1b] to-[#343434] px-5 text-sm font-semibold text-white shadow-[0_14px_35px_rgba(0,0,0,.24)] sm:hidden"><span className="alas-chat-icon grid h-7 w-7 place-items-center rounded-full bg-white/10" aria-hidden><svg viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M20 11.5a7.5 7.5 0 0 1-8 7.5 8.8 8.8 0 0 1-3.3-.65L4 20l1.55-4.1A7.1 7.1 0 0 1 4 11.5 7.5 7.5 0 0 1 12 4a7.5 7.5 0 0 1 8 7.5Z" /></svg></span><span className="alas-chat-label">Chat with ALAS</span></Link><button type="button" onClick={() => setOpen((value) => !value)} className="fixed bottom-5 right-5 z-50 hidden min-h-12 items-center gap-2 rounded-full border border-white/15 bg-gradient-to-r from-black via-[#1b1b1b] to-[#343434] px-5 text-sm font-semibold text-white shadow-[0_14px_35px_rgba(0,0,0,.24)] hover:shadow-[0_18px_42px_rgba(0,0,0,.32)] sm:flex" aria-expanded={open} aria-controls="alas-support-chat"><span className="alas-chat-icon grid h-7 w-7 place-items-center rounded-full bg-white/10" aria-hidden><svg viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M20 11.5a7.5 7.5 0 0 1-8 7.5 8.8 8.8 0 0 1-3.3-.65L4 20l1.55-4.1A7.1 7.1 0 0 1 4 11.5 7.5 7.5 0 0 1 12 4a7.5 7.5 0 0 1 8 7.5Z" /></svg></span><span className="alas-chat-label">Chat with ALAS</span></button></>}
    {(open || dedicated) && <section id="alas-support-chat" aria-label="ALAS Support chat" className={`fixed inset-0 z-[70] isolate flex h-[100dvh] min-h-0 flex-col overflow-hidden bg-white ${dedicated ? "" : "sm:inset-auto sm:bottom-20 sm:right-5 sm:h-[min(590px,calc(100dvh-6rem))] sm:w-[390px] sm:max-w-[calc(100vw-2rem)] sm:rounded-[28px] sm:border sm:border-black/[0.08] sm:shadow-[0_28px_80px_rgba(35,22,17,.22)]"}`}>
      <header className="relative flex flex-none items-center justify-between overflow-hidden border-b border-black/[0.06] bg-white px-4 pb-4 pt-[max(1rem,env(safe-area-inset-top))] sm:px-5 sm:py-4"><div className="pointer-events-none absolute inset-x-0 top-0 h-1 bg-gradient-to-r from-black via-[#2a2a2a] to-[#555]"/><div className="flex min-w-0 items-center gap-3"><div className="relative h-11 w-11 flex-none overflow-hidden rounded-full border border-black/10 bg-white shadow-[0_8px_20px_rgba(0,0,0,.16)]"><Image src="/blackspadelogo-transparent.png" alt="ALAS" fill sizes="44px" className="scale-[1.35] object-cover" priority /></div><div className="min-w-0"><h2 className="m-0 truncate text-base font-semibold text-[#171717]">ALAS Support</h2><p className="m-0 flex items-center gap-1.5 text-xs text-black/55"><span className={`h-2 w-2 rounded-full ${human ? "bg-orange-500" : connection === "connected" ? "bg-emerald-500" : "bg-red-500"}`}/>{human ? "Human support" : connection === "connected" ? "Online" : "Reconnecting…"}</p></div></div><button onClick={() => dedicated ? router.back() : setOpen(false)} className="grid h-10 w-10 flex-none place-items-center rounded-full border border-black/[0.07] bg-[#f7f5f3] text-black/60 shadow-none" aria-label={dedicated ? "Back" : "Close chat"}><svg aria-hidden="true" viewBox="0 0 24 24" className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{dedicated ? <path d="m15 5-7 7 7 7" /> : <path d="m5 5 14 14M19 5 5 19" />}</svg></button></header>
      {!conversation ? <div className="flex flex-1 flex-col items-center justify-center gap-5 bg-[radial-gradient(circle_at_top,rgba(0,0,0,.07),transparent_42%),linear-gradient(to_bottom,#fff,#f7f7f7)] p-8 text-center"><div className="grid h-16 w-16 place-items-center rounded-full bg-gradient-to-br from-zinc-100 to-zinc-200 shadow-inner"><svg aria-hidden="true" viewBox="0 0 24 24" className="h-7 w-7" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="M20 11.5a7.5 7.5 0 0 1-8 7.5 8.8 8.8 0 0 1-3.3-.65L4 20l1.55-4.1A7.1 7.1 0 0 1 4 11.5 7.5 7.5 0 0 1 12 4a7.5 7.5 0 0 1 8 7.5Z" /></svg></div><div><h3 className="m-0 text-lg font-semibold text-[#171717]">How can we help?</h3><p className="mt-2 text-sm leading-6 text-black/60">Ask about ALAS products, sizing, shipping, orders, or policies. No account is required.</p></div><button disabled={busy} onClick={start} className="min-h-12 rounded-full bg-gradient-to-r from-black via-[#1b1b1b] to-[#3a3a3a] px-7 text-sm font-semibold text-white shadow-[0_12px_28px_rgba(0,0,0,.20)] disabled:opacity-50">{busy ? "Connecting…" : "Start chat"}</button>{connection === "error" && <p role="alert" className="text-xs text-red-700">Support could not connect. Please try again.</p>}</div> : <>
        <div className="min-h-0 flex-1 space-y-3 overflow-y-auto overscroll-contain bg-[radial-gradient(circle_at_top_left,rgba(0,0,0,.055),transparent_35%),linear-gradient(to_bottom,#fafafa,#f0f0f0)] p-4 [scrollbar-gutter:stable]" aria-live="polite">{messages.map((message) => { const recommendations = message.payload?.products ?? []; if ((message.content_type === "PRODUCT_CARD" || message.content_type === "PRODUCT_CAROUSEL") && recommendations.length) return <div key={message.id} className={message.content_type === "PRODUCT_CAROUSEL" ? "flex snap-x gap-3 overflow-x-auto pb-2" : "flex w-full justify-start"}>{recommendations.map((recommendation) => { const product = cardProducts[recommendation.product_id]; return product ? <div key={recommendation.product_id} className="snap-start"><ChatProductCard product={product} initialVariantId={recommendation.variant_id} messageId={message.id} onAction={() => void load()} /></div> : <div key={recommendation.product_id} className="h-64 w-72 animate-pulse rounded-[22px] bg-white/70" />; })}</div>; return <div key={message.id} className={`flex w-full ${message.sender_type === "CUSTOMER" ? "justify-end" : "justify-start"}`}><div className={`max-w-[84%] px-4 py-3 text-sm leading-5 ${message.sender_type === "CUSTOMER" ? "rounded-[22px_7px_22px_22px] bg-gradient-to-br from-black via-[#1d1d1d] to-[#414141] text-white shadow-[0_10px_26px_rgba(0,0,0,.18)]" : message.content_type === "ACTION_RESULT" ? "rounded-[16px] bg-emerald-50 text-emerald-800 shadow-[0_8px_24px_rgba(5,150,105,.08)]" : "rounded-[7px_22px_22px_22px] border border-white/90 bg-white/95 text-black shadow-[0_8px_28px_rgba(0,0,0,.07)] backdrop-blur-xl"}`}><p className="m-0 whitespace-pre-wrap break-words">{message.content}</p>{message.delivery_status === "PENDING" && <span className="mt-1 block text-[10px] opacity-60">Sending…</span>}{message.delivery_status === "FAILED" && <span className="mt-1 block text-[10px] text-white/80">Failed — send again</span>}</div></div>; })}{aiTyping && <div className="flex w-full justify-start"><div role="status" aria-label="ALAS Assistant is typing" className="flex w-fit items-center gap-1.5 rounded-[7px_22px_22px_22px] border border-white/90 bg-white/95 px-4 py-3.5 shadow-[0_10px_30px_rgba(0,0,0,.07)] backdrop-blur-xl"><span className="sr-only">ALAS Assistant is typing…</span>{[0, 1, 2].map((dot) => <span key={dot} aria-hidden className="h-2 w-2 animate-bounce rounded-full bg-gradient-to-br from-black to-[#555] motion-reduce:animate-none" style={{ animationDelay: `${dot * 140}ms`, animationDuration: "850ms" }} />)}</div></div>}<div ref={bottom} /></div>
        <form onSubmit={send} className="border-t border-black/[0.06] bg-white/95 p-2.5 pb-[max(.625rem,env(safe-area-inset-bottom))] backdrop-blur-xl sm:p-3"><div className="flex items-end gap-2 rounded-[24px] border border-black/[0.07] bg-[#f2f2f2] p-1.5 shadow-inner"><label className="sr-only" htmlFor="support-message">Message</label><textarea id="support-message" value={text} onChange={(event) => setText(event.target.value)} rows={1} maxLength={2000} className="min-h-11 max-h-28 min-w-0 flex-1 resize-none border-0 bg-transparent px-3 py-3 text-[16px] leading-5 outline-none ring-0 focus:ring-0" placeholder="Type your message…"/><button type="submit" disabled={!text.trim() || busy} className="grid h-11 min-h-11 w-11 flex-none place-items-center rounded-full bg-gradient-to-br from-black via-[#1d1d1d] to-[#444] p-0 text-white shadow-[0_9px_22px_rgba(0,0,0,.22)] disabled:cursor-not-allowed disabled:opacity-35" aria-label="Send message"><svg className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24" aria-hidden><path d="m22 2-7 20-4-9-9-4Z"/><path d="M22 2 11 13"/></svg></button></div></form>
      </>}</section>}
  </>;
}
