"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { useCartStore } from "@/features/cart/cart-store";
import type { Product } from "@/types/catalog";

export function AddToCart({ product, showCheckout = false }: { product: Product; showCheckout?: boolean }) {
  const router = useRouter();
  const available = product.variants.filter((variant) => variant.stock > 0); const [variantId, setVariantId] = useState(available[0]?.id ?? ""); const [notice, setNotice] = useState(""); const addItem = useCartStore((state) => state.addItem); const selected = product.variants.find((variant) => variant.id === variantId);
  if (!selected) return <p className="mt-8 border border-black/20 px-5 py-4 text-center text-xs uppercase tracking-[.14em]">Sold out</p>;
  const addSelected = () => { addItem({ variantId: selected.id, productSlug: product.slug, productName: product.name, image: product.image, size: selected.size, color: selected.color, displayPriceCentavos: selected.priceCentavos, quantity: 1 }); setNotice("Added to bag"); };
  return <div className="mt-7"><div className="flex items-center justify-between"><span className="text-[10px] uppercase tracking-[.1em]">Size</span><button className="border-b border-black/60 text-[10px] uppercase tracking-[.08em]">Size guide</button></div><div className="mt-3 grid grid-cols-5 gap-2">{product.variants.map((variant) => <button key={variant.id} disabled={variant.stock === 0} onClick={() => setVariantId(variant.id)} className={`h-10 border text-xs transition ${variant.id === variantId ? "border-black bg-black text-white" : "border-black/15 hover:border-black/50"} disabled:text-black/30 disabled:line-through`}>{variant.size}</button>)}</div><div className={showCheckout ? "mt-6 grid grid-cols-2 gap-2" : "mt-6"}><button onClick={addSelected} className="flex h-12 w-full items-center justify-center gap-2 bg-black px-4 text-[10px] font-semibold uppercase tracking-[.14em] text-white transition hover:bg-[#bb152c]">Add to bag <svg aria-hidden="true" viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M5 12h14M13 6l6 6-6 6" /></svg></button>{showCheckout && <button onClick={() => { addSelected(); router.push("/checkout"); }} className="h-12 border border-black bg-white px-4 text-[10px] font-semibold uppercase tracking-[.14em] text-black">Buy now</button>}</div><button className="mt-2.5 flex h-11 w-full items-center justify-center gap-2 border border-black/15 px-5 text-[10px] uppercase tracking-[.14em] transition hover:border-black/40"><svg aria-hidden="true" viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d="M20.8 4.8a5.5 5.5 0 0 0-7.8 0L12 5.9l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.4a5.5 5.5 0 0 0 0-7.8Z" /></svg> Save to wishlist</button>{notice && <p role="status" className="mt-3 text-center text-[10px] uppercase tracking-[.14em]">{notice}</p>}</div>;
}
