"use client";
import { useState } from "react";
import { useCartStore } from "@/features/cart/cart-store";
import type { Product } from "@/types/catalog";

export function AddToCart({ product }: { product: Product }) {
  const available = product.variants.filter((variant) => variant.stock > 0); const [variantId, setVariantId] = useState(available[0]?.id ?? ""); const [notice, setNotice] = useState(""); const addItem = useCartStore((state) => state.addItem); const selected = product.variants.find((variant) => variant.id === variantId);
  if (!selected) return <p className="mt-8 border border-black/20 px-5 py-4 text-center text-xs uppercase tracking-[.14em]">Sold out</p>;
  return <div className="mt-7"><div className="flex items-center justify-between"><span className="text-[10px] uppercase tracking-[.1em]">Size</span><button className="border-b border-black/60 text-[10px] uppercase tracking-[.08em]">Size guide</button></div><div className="mt-3 grid grid-cols-5 gap-2">{product.variants.map((variant) => <button key={variant.id} disabled={variant.stock === 0} onClick={() => setVariantId(variant.id)} className={`h-10 border text-xs transition ${variant.id === variantId ? "border-black bg-black text-white" : "border-black/15 hover:border-black/50"} disabled:text-black/30 disabled:line-through`}>{variant.size}</button>)}</div><button onClick={() => { addItem({ variantId: selected.id, productSlug: product.slug, productName: product.name, image: product.image, size: selected.size, color: selected.color, displayPriceCentavos: selected.priceCentavos, quantity: 1 }); setNotice("Added to bag"); }} className="mt-6 h-12 w-full bg-black px-5 text-[10px] font-semibold uppercase tracking-[.16em] text-white transition hover:bg-[#bb152c]">Add to bag →</button><button className="mt-2.5 h-11 w-full border border-black/15 px-5 text-[10px] uppercase tracking-[.14em] transition hover:border-black/40">♡ &nbsp; Save to wishlist</button>{notice && <p role="status" className="mt-3 text-center text-[10px] uppercase tracking-[.14em]">{notice}</p>}</div>;
}
